#!/bin/bash

fetch_hg_repo()
{
    if [ -d $2 ] ; then
        (cd $2; hg pull -u $1)
    else
        hg clone $1 $2
    fi
}


cd ../experimental
set -ev

# Add ngene & octopus
fetch_hg_repo "http://linuxtv.org/hg/~endriss/ngene-octopus-test" "ngene-octopus-test"
rm -Rf ../linux/drivers/media/dvb/{ddbridge,ngene} ../linux/drivers/staging/media/cxd2099 ../linux/drivers/staging/cxd2099
cp -r ngene-octopus-test/linux/drivers/media/dvb/{ddbridge,ngene} ../linux/drivers/media/dvb/
cp -r ngene-octopus-test/linux/drivers/staging/cxd2099 ../linux/drivers/staging/media/
cp ngene-octopus-test/linux/drivers/media/dvb/frontends/tda18212dd* ../linux/drivers/media/dvb/frontends/
cp ngene-octopus-test/linux/drivers/media/dvb/frontends/stv0367dd*  ../linux/drivers/media/dvb/frontends/
patch -d.. -p0 < stv0367dd-tda18212dd.frontend-kconfig.diff
patch -d.. -p0 < stv0367dd-tda18212dd.frontend-makefile.diff
cp -r drxk/* ../linux/drivers/media/dvb/frontends/

# Add TT DVB S2-6400
fetch_hg_repo "http://powarman.dyndns.org/hg/v4l-dvb-saa716x" "v4l-dvb-saa716x" || fetch_hg_repo "http://linuxtv.org/hg/~endriss/mirror-saa716x" "v4l-dvb-saa716x"
rm -Rf ../linux/drivers/media/common/saa716x
cp -r v4l-dvb-saa716x/linux/drivers/media/common/saa716x  ../linux/drivers/media/common
patch -d.. -p0 < saa716x.common-kconfig.diff
patch -d.. -p0 < saa716x.common-makefile.diff
patch -d.. -p0 < saa716x.include-osd.diff

# Preliminary patch: Provide stv090x BER/UCB stats.
patch -d.. -p0 < stv090x_ucblocks_ber.diff

# Preliminary patch: Do not access registers of second path on stv0903.
patch -d../linux -p1 < stv090x_stv0903_not_set_registers_of_second_path.diff

# Preliminary patch: Remove lock status warning.
patch -d.. -p0 < drxk_lockstatus_fix.diff

# Preliminary patch: Remove qam_demod_parameter_count.
patch -d.. -p0 < em28xx_remove_parmcnt.diff
# Drivers added successfully ;-)
