#!/bin/bash

fetch_hg_repo()
{
  {
    if [ -d $2 ] ; then
        (cd $2; hg pull -u $1)
    else
        hg clone $1 $2
    fi
  } && hg tip -R $2 --template "$2: {node} {desc|firstline}\n" >> ../linux/git_log
}

apply_patch()
{
    patch -d.. -p0 -f --dry-run < $1 &> /dev/null && patch -d.. -p0 < $1 && return 0
    patch -d.. -p1 -f --dry-run < $1 &> /dev/null && patch -d.. -p1 < $1 && return 0
    echo "*** Failed to apply '$1'! ***"
    return 1
}


cd ../experimental
hg tip --template "experimental: {node} {desc|firstline}\n" >> ../linux/git_log

set -ev

# Add ngene & octopus
rm -Rf ../linux/drivers/media/pci/{ddbridge,ngene} ../linux/drivers/staging/media/cxd2099/cxd2099*
cp -r dddvb/ddbridge ../linux/drivers/media/pci/
cp    oe/ddbridge/*  ../linux/drivers/media/pci/ddbridge/
cp -r oe/ngene       ../linux/drivers/media/pci/
# frontends
cp dddvb/frontends/cxd2099*    ../linux/drivers/staging/media/cxd2099/
cp dddvb/frontends/tda18212dd* ../linux/drivers/media/dvb-frontends/
cp dddvb/frontends/stv0367dd*  ../linux/drivers/media/dvb-frontends/
cp oe/drxk/*                   ../linux/drivers/media/dvb-frontends/
cp dddvb/frontends/cxd2843*    ../linux/drivers/media/dvb-frontends/
# dvb-core extensions
cp dddvb/include/linux/dvb/mod.h   ../linux/include/uapi/linux/dvb/
cp dddvb/include/linux/dvb/ns.h    ../linux/include/uapi/linux/dvb/
cp dddvb/dvb-core/dvb_netstream.*  ../linux/drivers/media/dvb-core/

# Add TT DVB S2-6400
fetch_hg_repo "https://bitbucket.org/powARman/v4l-dvb-saa716x" "v4l-dvb-saa716x" ||
 fetch_hg_repo "http://powarman.dyndns.org/hg/v4l-dvb-saa716x" "v4l-dvb-saa716x" ||
 fetch_hg_repo "http://linuxtv.org/hg/~endriss/mirror-saa716x" "v4l-dvb-saa716x"
rm -Rf ../linux/drivers/media/pci/saa716x
cp -r v4l-dvb-saa716x/linux/drivers/media/common/saa716x  ../linux/drivers/media/pci/
patch -d.. -p0 < saa716x.pci-kconfig.diff
patch -d.. -p0 < saa716x.pci-makefile.diff
patch -d.. -p0 < saa716x.include-osd.diff

for i in patch.d/*diff ;
do
    echo
    echo "Applying '$i'"
    apply_patch $i
done

# Drivers added successfully ;-)
